### ISSUE TITLE
[REVIEW] An evaluation of mouse and keyboard interaction indicators towards non-intrusive and low cost affective modeling in an educational context

### ISSUE THREAD

**Issue by hodTwito** [capi-bgu/Research#26]
### Paper Details
**Link**: https://www.sciencedirect.com/science/article/pii/S1877050914011168
**Date**: 2014
**Topic**: An evaluation of mouse and keyboard interaction indicators towards non-intrusive and low cost affective modeling in an educational context

**Comment by yuvalkh** [comment]
- history of works that tried with keyboard/mouse and other equipments.
- mouse features and keyboard features.
- in the experiment they let 75 people solve math problems and took their mouse and keyboard. after that they tried some algorithms and if should combine the mouse and the keyboard models.
- tells that dimensional approach ( scale of emotions) can give different results than categorical approach(name of emotions)

**Comment by yuvalkh** [comment]
[An evaluation of mouse and keyboard interaction indicators towards non-intrusive and low cost affective modeling in an educational context.pdf](https://github.com/capi-bgu/Research/files/5683551/An.evaluation.of.mouse.and.keyboard.interaction.indicators.towards.non-intrusive.and.low.cost.affective.modeling.in.an.educational.context.pdf)

Used that paper in related work
