### ISSUE TITLE
[REVIEW] Affective Computing – A Rationale for Measuring Mood with Mouse and Keyboard 

### ISSUE THREAD

**Issue by hodTwito** [capi-bgu/Research#29]
### Paper Details
**Link**: https://www.researchgate.net/publication/8958741_Affective_Computing-A_Rationale_for_Measuring_Mood_With_Mouse_and_Keyboard
**Date**: Feb 2003
**Topic**: affective computing using mouse and keyboard

the first article about keyboard and mouse based emotion detection field

**Comment by hodTwito** [comment]
Notes:
- method for the measurement of affective states through
motor-behavioral parameters from the standard input devices mouse and
keyboard
- about affect, emotion and mood
- about the connection to Neuropsychology
- Mood Measurement Methods
- suggested features

important to read

**Comment by yuvalkh** [comment]
[Affective_Computing-A_Rationale_for_Measuring_Mood.pdf](https://github.com/capi-bgu/Research/files/5612642/Affective_Computing-A_Rationale_for_Measuring_Mood.pdf)
