### ISSUE TITLE
[REVIEW] Reading Emotion From Mouse Cursor Motions: Affective Computing Approach

### ISSUE THREAD

**Issue by hodTwito** [capi-bgu/Research#30]
### Paper Details
**Link**: https://onlinelibrary.wiley.com/doi/full/10.1111/cogs.12557
**Date**: Nov 2017
**Topic**: Reading Emotion From Mouse Cursor Motions: Affective Computing Approach

**Comment by yuvalkh** [comment]
This thing is very long and we will read if we need more information
