### ISSUE TITLE
[REVIEW] Towards Improving Visual-Facial Emotion Recognition through Use of Complementary Keyboard-Stroke Pattern Information

### ISSUE THREAD

**Issue by hodTwito** [capi-bgu/Research#35]
### Paper Details
**Link**: http://edge.rit.edu/edge/P10002/public/On%20Improving%20Visual-Facial%20Emotion%20Recognition%20with%20Audio-lingual%20and%20Keyboard%20Stroke%20Pattern%20Information
**Date**: 2008
**Topic**: Towards Improving Visual-Facial Emotion Recognition through Use of
Complementary Keyboard-Stroke Pattern Information

**Comment by yuvalkh** [comment]
- History of face recognition studies.
- Choosing features from the keyboard.
- Typing speed is an important feature.
- Backspace and unrelated keys are important features.
- Using both visual-facial and keyboard to recognize emotions can improve accuracy.

**Comment by yuvalkh** [comment]
[On Improving Visual-Facial Emotion Recognition with Audio-lingual and Keyboard Stroke Pattern Information.pdf](https://github.com/capi-bgu/Research/files/5615011/On.Improving.Visual-Facial.Emotion.Recognition.with.Audio-lingual.and.Keyboard.Stroke.Pattern.Information.pdf)
no features/models was presented
Was very emperical

**Comment by yuvalkh** [comment]
Didn't use that paper in the work.
