### ISSUE TITLE
[REVIEW] TapSense: Combining Self-Report Patterns and Typing Characteristics for Smartphone based Emotion Detection

### ISSUE THREAD

**Issue by Zshoham** [capi-bgu/Research#38]
### Paper Details
**Link**: https://surjya-ghosh.github.io/Surjya_Ghosh_files/papers/2017_MobileHCI_TapSense.pdf
**Date**: 2017
**Topic**: Personalized machine learning for smartphone keyboard based emotion recognition.

**Comment by yuvalkh** [comment]
In this paper they use smartphones so it **contains only keyboard**

- Predict only happy-sad / stressed-relaxed.
- How to process the data.
- Which features should get.
- Getting the data from the users.
- Features of keystroke, and what are the best.
- Using SMOTE to improve accuracy.
- Which model is the best.
- Personalized model vs aggregate model.

**Comment by yuvalkh** [comment]
[TapSense Combining Self-Report Patterns and Typing Characteristics for Smartphone based Emotion Detection.pdf](https://github.com/capi-bgu/Research/files/5614804/TapSense.Combining.Self-Report.Patterns.and.Typing.Characteristics.for.Smartphone.based.Emotion.Detection.pdf)

**Comment by hodTwito** [comment]
[TapSense_Combining_Self_Report_Patterns_and_Typing_Characteristics.pdf](https://github.com/capi-bgu/Research/files/5683534/TapSense_Combining_Self_Report_Patterns_and_Typing_Characteristics.pdf)
