### ISSUE TITLE
[REVIEW] Objective of Keystroke Dynamics for Identifying Emotional State 

### ISSUE THREAD

**Issue by Zshoham** [capi-bgu/Research#40]
### Paper Details
**Link**: http://ijcsit.com/docs/Volume%206/vol6issue01/ijcsit20150601139.pdf
**Date**: 2015
**Topic**: Feasibility of Emotion Recognition Using Keyboard and Mouse

**Comment by yuvalkh** [comment]
- The definition of emotion.
- Problems of emotion recognition
- Getting data by fixed text or free text
- Features that can be extracted from the data
- Labeling the data

**Comment by yuvalkh** [comment]
[Objective of Keystroke Dynamics for Identifying Emotional State.pdf](https://github.com/capi-bgu/Research/files/5614800/Objective.of.Keystroke.Dynamics.for.Identifying.Emotional.State.pdf)

**Comment by yuvalkh** [comment]
Didn't use that paper in the work but we can still search some features from there
