### ISSUE TITLE
[REVIEW] Keystroke/mouse usage based emotion detection and user identification

### ISSUE THREAD

**Issue by hodTwito** [capi-bgu/Research#44]
### Paper Details
**Link**: https://www.researchgate.net/publication/315865602_Keystrokemouse_usage_based_emotion_detection_and_user_identification
**Date**: JAN 2017
**Topic**:  Keystroke and mouse usage based emotion detection and user identification

**Comment by yuvalkh** [comment]
- Features of keyboard/mouse
- in their experiment they used bounded K-means classifer model that they made. But it in the results other algorithms were better such as: RandomCommittee, RandomForest, Bagging.
- in their experiment they tried to predict different things like: 10 emotions at start, positive or negative emotion.

**Comment by yuvalkh** [comment]
[Keystroke and mouse usage based emotion detection and user identification.pdf](https://github.com/capi-bgu/Research/files/5614797/Keystroke.and.mouse.usage.based.emotion.detection.and.user.identification.pdf)

**Comment by yuvalkh** [comment]
Didn't use that paper in the work.
