### ISSUE TITLE
[REVIEW] Emotions and User Interactions with  Keyboard and Mouse 

### ISSUE THREAD

**Issue by hodTwito** [capi-bgu/Research#45]
### Paper Details
**Link**: https://www.researchgate.net/publication/321383886_Emotions_and_User_Interactions_with_Keyboard_and_Mouse
**Date**: AUG 2017
**Topic**: correlation betwreen emotions and user Interactions with  keyboard and mouse

**Comment by hodTwito** [comment]
[Emotions_Keystroke_Mouse_IISA2017 (2).pdf](https://github.com/capi-bgu/Research/files/5595611/Emotions_Keystroke_Mouse_IISA2017.2.pdf)

**Comment by yuvalkh** [comment]
Used that paper in Related Work
